spring.application.name=ntpproject

openai.api.key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:h2:file:./data/projedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=duman
spring.datasource.password=duman

# 2. JPA Ayarlar? (Gerekirse):
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# ddl-auto: update (mevcut tablolar? koru ve yenilerini ekle)
spring.jpa.hibernate.ddl-auto=update

# 3. H2 Konsolunu Açma (Veriyi kontrol etmek için faydal?d?r):
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
admin.master.password=irfan.duman