spring.application.name=ntpproject
openai.api.key=${OPENAI_API_KEY}
spring.datasource.url=jdbc:h2:file:./data/projedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=duman
spring.datasource.password=duman
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
admin.master.password=rfn.duman